version: '3'

services:
  db_tests:
    image: "postgres:latest"
    restart: always
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=tests
    ports:
      - '5433:5432'
